name: onlinecourse
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.7.2+3
  flutter_native_splash: ^2.0.1+1
  internet_connection_checker: ^1.0.0+1
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.6
  shared_preferences: ^2.2.3
  webview_flutter: ^4.5.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.3
  http: ^1.1.0

#dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: "assets/play_store_512.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
# flutter pub run flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/play_store_512.png"
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
